language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t abdul/multi-container-dev -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true abdul/multi-container-dev npm run test -- --coverage

after_success:
  - docker build -t abdullahshboul/multi-container-client ./client
  - docker build -t abdullahshboul/multi-container-proxy ./proxy
  - docker build -t abdullahshboul/multi-container-server ./server
  - docker build -t abdullahshboul/multi-container-worker ./worker
  - echo "$DOCKER_PWD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push abdullahshboul/multi-container-client
  - docker push abdullahshboul/multi-container-server
  - docker push abdullahshboul/multi-container-proxy
  - docker push abdullahshboul/multi-container-worker
